import hydra_dx

public enum HydraOmnipoolMath {
    public static func omnipoolCalculateOutGivenIn<GenericIntoRustString: IntoRustString>(_ asset_in_reserve: GenericIntoRustString, _ asset_in_hub_reserve: GenericIntoRustString, _ asset_in_shares: GenericIntoRustString, _ asset_out_reserve: GenericIntoRustString, _ asset_out_hub_reserve: GenericIntoRustString, _ asset_out_shares: GenericIntoRustString, _ amount_in: GenericIntoRustString, _ asset_fee: GenericIntoRustString, _ protocol_fee: GenericIntoRustString, _ max_slip_fee: GenericIntoRustString) -> RustString {
        RustString(ptr: __swift_bridge__$omnipool_calculate_out_given_in({ let rustString = asset_in_reserve.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = asset_in_hub_reserve.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = asset_in_shares.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = asset_out_reserve.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = asset_out_hub_reserve.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = asset_out_shares.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = amount_in.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = asset_fee.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = protocol_fee.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = max_slip_fee.intoRustString(); rustString.isOwned = false; return rustString.ptr }()))
    }
    public static func omnipoolCalculateInGivenOut<GenericIntoRustString: IntoRustString>(_ asset_in_reserve: GenericIntoRustString, _ asset_in_hub_reserve: GenericIntoRustString, _ asset_in_shares: GenericIntoRustString, _ asset_out_reserve: GenericIntoRustString, _ asset_out_hub_reserve: GenericIntoRustString, _ asset_out_shares: GenericIntoRustString, _ amount_out: GenericIntoRustString, _ asset_fee: GenericIntoRustString, _ protocol_fee: GenericIntoRustString, _ max_slip_fee: GenericIntoRustString) -> RustString {
        RustString(ptr: __swift_bridge__$omnipool_calculate_in_given_out({ let rustString = asset_in_reserve.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = asset_in_hub_reserve.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = asset_in_shares.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = asset_out_reserve.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = asset_out_hub_reserve.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = asset_out_shares.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = amount_out.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = asset_fee.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = protocol_fee.intoRustString(); rustString.isOwned = false; return rustString.ptr }(), { let rustString = max_slip_fee.intoRustString(); rustString.isOwned = false; return rustString.ptr }()))
    }
}
